### ISSUE TITLE
Git Repo size too abnormally large

### ISSUE THREAD

**Issue by Sridou** [end-4/dots-hyprland#124]
I cloned the repo using  `git clone -b illogical-impulse https://github.com/end-4/dots-hyprland` and this is the result: 
```
Cloning into 'dots-hyprland'...
remote: Enumerating objects: 44301, done.
remote: Counting objects: 100% (44301/44301), done.
remote: Compressing objects: 100% (15639/15639), done.
remote: Total 44301 (delta 24659), reused 44224 (delta 24625), pack-reused 0
Receiving objects: 100% (44301/44301), 717.72 MiB | 19.31 MiB/s, done.
Resolving deltas: 100% (24659/24659), done.
```
I looked into it and found 

 `.git/objects/pack/pack-a62c6c93368d669f5b554eb6a7e13a09b556c8ed.pack` is 717.17 MiB. Is it normal? I don't know much about git.

**Comment by end-4** [comment]
hmm. let me see what i can do
maybe stop bundling the icons and stop storing images in `assets` folder will help

**Comment by end-4** [comment]
Man, it's been 2 weeks... I tried `git-filter-repo` but then had issues with authentication and was frustrated so I forgot about it.
I'm just going to update that the repo size went down to around 550mb.
I'll probably just delete every branch and then create them again, since I pretty much use this repo like a Google Drive and commit history doesn't really matter lol.

**Comment by end-4** [comment]
I fixed it!
Ended up destroying everything and reupload, but it worked
The size is now 14mb
