### ISSUE TITLE
wifi does not connect, only if i manually start nm-applet

### ISSUE THREAD

**Issue by fsyy** [end-4/dots-hyprland#133]
- **I have read the instructions** and I have a problem with branch: 
illogical-impulse

## The issue
- i have kde and hyprland installed and use sddm. If i log in to hyprland my wifi is not activated, it only works after i manually start nm-applet. 
- i guess my saved wifi networks from kwallet are not working as this setup uses gnome-keyring, which would not be an issue for now, but i cannot even connect to a network without first starting nm-applet
- any hints where to look for that issue?

**Comment by end-4** [comment]
## Wifi
- I believe network connection is something you have to set up at system level, which I'm unsure of, since I use EndeavourOS Gnome. I used `nmtui` to connect to the desired network once and it just worked since then. 
  - Hint: I've heard people saying that with AGS, you should use NetworkManager, not systemd-networkd. 
  - My config only provides customization at user level and doesn't serve as a complete solution for a fresh raw Arch install. The wifi button on the sidebar just toggles wifi, it doesn't  do anything else.
 ## Keyring
- That's something you have to figure out. I'm a Gnome guy.

i probably should recommend gnome stuff in the instructions...
anyway, good luck!

**Comment by fsyy** [comment]
ok i will try nmtui then, seems that as i set it up with nm-applet i will have to run nm-applet to make it auto connect. 

I will try a few things, i was confused as it didn*t ask for passwords even when i tried a new network in the gnome settings. I will figure that out. I just thought as i had it set up with network-manager in kde it should just work, that could then be an keyring issue.

Thanks for your answer.
