### ISSUE TITLE
What is the source of Droidbars  Hyrpland plugin?

### ISSUE THREAD

**Issue by AnhQuanTrl** [end-4/dots-hyprland#134]
I noticed in the repo there is a `droidbars.so` plugin and cannot find it in the internet. Is it an open source plugin? It is a bit dangerous to execute a `so` file without knowing the source.

**Comment by end-4** [comment]
- Oh, it's my modded version of [hyprbars](https://github.com/hyprwm/hyprland-plugins/tree/main/hyprbars)
- I made that for fun but never publicized its source since it's a little bit hacky and unfinished
  - Currently, the binary won't even work (due to version mismatch) and the source code won't even compile (due to breaking changes in hyprland's source) anyway
- I'll remove that file, thanks for telling me

**Comment by end-4** [comment]
https://github.com/end-4/dots-hyprland/commit/f70ae812e9b25818f00f013b5f80173df04a6f2a
also a friendly reminder to you that you shouldn't use the main branch
