### ISSUE TITLE
Notif action btn size and DND; Battery indicator fallback

### ISSUE THREAD

**Issue by bThiiago** [end-4/dots-hyprland#163]
I think it would be good if the actions button size could be dynamic, as you can see in my print, the "Mark as read" overlaps the button and increases the sidebar size a little.

Also two things i think should be good to implement: 
Do not disturb function in the quick toggles as you can see in the print, i used the Notifications.dnd by the ags service (really good to turn on when watching or playing);
And make a fallback for desktop users to show again the memory usage in the system module instead of brightness.

![20240102_12h11m46s_grim](https://github.com/end-4/dots-hyprland/assets/52681481/ec26e8d8-6627-471c-9e63-405205003fd5)

**Comment by end-4** [comment]
all reasonable, added to my todo list
## Action button sizes
- Shouldn't be hard, but first I gotta figure out how to create notifications with actions lol
## Dnd
- Right, that should also be simple. But I'm having a different design in mind: show it next to "Clear" button (when there are notifs) or under the "No notifications" text that's to be made
## Battery fallback
- I had a redesign of the bar and haven't bothered to bring back the fallback resource displays yet, but I will

**Comment by end-4** [comment]
button size fixed https://github.com/end-4/dots-hyprland/commit/705da5e6ad37c62567e56f1ad31e73d8966ef201
![image](https://github.com/end-4/dots-hyprland/assets/97237370/14133a54-ab00-4741-92ae-96447e716435)

**Comment by end-4** [comment]
- Notif DND done: https://github.com/end-4/dots-hyprland/commit/fb5d6655877e68d473a5ce0d9a500612c23e24be

https://github.com/end-4/dots-hyprland/assets/97237370/6c3bb8c2-e7f9-4612-ad8f-3d622a0b10cd

- I prefer the word "Silence" because "Do not disturb" is too long and I'd rather not use a fully capitalized "DND" or insufficiently capitalized "Dnd"
---
- Anyway, there's just the battery fallback left
  - I think I'll put RAM/Swap usage as 2 pills with circular progress like what the battery module currently looks like

**Comment by end-4** [comment]
Done!
What do y'all think?
![image](https://github.com/end-4/dots-hyprland/assets/97237370/95209f6d-42e7-4793-8f8c-b7e7c0e3b440)

**Comment by bThiiago** [comment]
Really good, everything looks better than I expected, thank you!

**Comment by end-4** [comment]
Alright
Since you're happy I'm going to close this
