### ISSUE TITLE
How to disable autolock and auto sleep

### ISSUE THREAD

**Issue by AdityaRoot** [end-4/dots-hyprland#164]
Apologies for the super basic question! Just didn't find anything in the wiki nor after changing the gnome settings.

Would love a way to disable/modify the autosleep and autolock durations and times - as the laptop autolocks even when watching a movie!

Thank you for the gorgeous dots :)

**Comment by end-4** [comment]
- Gnome settings won't work since you're not in Gnome
- To fully disable or modify, edit/remove the lines that start with `exec-once = swayidle` in `~/.config/hypr/execs.conf`
- **But**, for your case of not having lock/sleep trigger while watching a movie, just turn on the coffee button on the right sidebar
![image](https://github.com/end-4/dots-hyprland/assets/97237370/c1102e0d-89c3-40a2-8b9a-94c8c8d375ea)

**Comment by AdityaRoot** [comment]
Ah I see the relevant lines, perfect, thank you so much!

**Comment by clsty** [comment]
> But, for your case of not having lock/sleep trigger while watching a movie, just turn on the coffee button on the right sidebar

I'm wondering that where is the `wayland-idle-inhibitor.py` file used by that button in `.config/ags/widgets/sideright/quicktoggles.js` .

**Comment by end-4** [comment]
> I'm wondering that where is the wayland-idle-inhibitor.py file used by that button in .config/ags/widgets/sideright/quicktoggles.js .

`yay -S wayland-idle-inhibitor-git`
(added in #145)
