### ISSUE TITLE
[Issue trying to configure the chatgpt  client but i cant 

### ISSUE THREAD

**Issue by alavaelian** [end-4/dots-hyprland#166]
i just keep getting the error that i run out of credits for using the api but i still have full of them

**Comment by alavaelian** [comment]
oh i need to check that, in the mean time can you tell me how to configure the chatgpt client just to be sure that i am doing it correctly

**Comment by clsty** [comment]
> For now there was a pull request here like some improvements to chatgpt API see https://github.com/end-4/dots-hyprland/pull/170

Welp, I guess the PR won't help on this condition.
The PR is actually something partly like [this one](https://github.com/openai/openai-python/issues/547).

**Comment by clsty** [comment]
Situation now on this topic has changed much.
I'm closing this issue since it's outdated.

See [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage/) and the comments in `~/.config/ags/user_options.js` for some references. This [issue](https://github.com/end-4/dots-hyprland/issues/152) may also helps.

Feel free to reopen if you still got the same problem.
