### ISSUE TITLE
[Issue] Problems for new wallpaper loader

### ISSUE THREAD

**Issue by clsty** [end-4/dots-hyprland#200]
- **I have read the instructions**
---
### Minor
I noticed that now wallpaper moves a bit every time the workspace is switched.
While this is a nice feature (it's really cool!), however it still behaves weird for multiple monitors.

When a workspace on monitor A is selected, the wallpaper on the monitor B will move.
But, well, this is just a minor problem.
### Major
There are two major problems I've encountered:
1. I'm using dual monitors, and only the monitor with ags bar on it displays the wallpaper, and the background of another monitor just went black.
2. [Solved] Although I've loaded a wallpaper already (and it's displayed normally, though only on one monitor), the prompt `No wallpaper loaded` with the button `Select One` still presents (and yes, still on that monitor with ags bar on it).

**Comment by end-4** [comment]
- Honestly I'm not sure how much freedom I should give users with this new wallpaper implementation
  - It was built with multiple monitors in mind (there's a json array for the list of wallpapers), but if selecting a new wallpaper is supposed to generate new colors, ... well, I think you can see the problem here if we allow different walls on different monitors.
- But at least I should make the Wallpaper service expand to the number of monitors, which I will do.

**Comment by clsty** [comment]
Great, now that the majar problem 2 disappeared.

**Comment by clsty** [comment]
Since now swww is used again, I'll close this issue for now. Feel free to reopen it when needed. @end-4
