### ISSUE TITLE
[Feature] Enable copy to clipboard for notifications

### ISSUE THREAD

**Issue by clsty** [end-4/dots-hyprland#224]
**What would you like to be added?**
Enable copy content of notification to clipboard.
- Maybe add a "Copy" button on each notification.
- Or, enable selection on the text (so that user can copy them by pressing `Ctrl+C` or `Ctrl+Shift+C`).

**How will it help**
E.g. when such notification pops up like https://github.com/end-4/dots-hyprland/issues/222#issuecomment-1920368772 , user will be able to copy it, not screenshot or take a picture of it.

**Comment by end-4** [comment]
### hmm
- I don't like an extra button since imo there are already enough
- Selection won't work because it would break gestures
  - Then I thought: gestures -> hmm mobile -> copying on mobile? -> touch and hold!

... So now if you click and hold a notif for 800ms its content will be copied
### video
https://github.com/end-4/dots-hyprland/assets/97237370/e339c208-5d80-4812-add8-e031bb9e9eac

**Comment by clsty** [comment]
> Then I thought: gestures -> hmm mobile -> copying on mobile? -> touch and hold!

That's a nice thought.


I've tried it. It's a very cool design! Thanks!
