### ISSUE TITLE
[Issue] Right-clicking the system tray will trigger music switching

### ISSUE THREAD

**Issue by gitttyyy** [end-4/dots-hyprland#329]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: archlinux

---
## The issue

<details>
<summary>Click to expand</summary>

The music switching trigger range is a bit too wide, so that right-clicking the system tray will trigger music switching.

</details>

**Comment by end-4** [comment]
Right-clicking there triggering both is a GTK/AGS problem
You can left-click for the tray item, though. I could disable right-click for them

**Comment by TwelveNight** [comment]
> Right-clicking there triggering both is a GTK/AGS problem You can left-click for the tray item, though. I could disable right-click for them Key-click the tray item. I can disable their right click

Then this is indeed a problem, because the tray behavior of some applications cannot be completed only through the menu. For example, some application`s GUI can be brought up by left-clicking. There is no option to start the GUI in the right-clicking tray. For this reason, I changed the left-clicking function to active it GUI or other specific function.Fortunately, there are not many apps like this

**Comment by TwelveNight** [comment]
Then this is indeed a problem, because the tray behavior of some applications cannot be completed only through the menu. For example, some application`s GUI can be brought up by left-clicking. There is no option to start the GUI in the right-clicking tray. For this reason, I changed the left-clicking function to active it GUI or other specific function.Fortunately, there are not many apps like this

**Comment by end-4** [comment]
> Then this is indeed a problem, because the tray behavior of some applications cannot be completed only through the menu. For example, some application`s GUI can be brought up by left-clicking. There is no option to start the GUI in the right-clicking tray. For this reason, I changed the left-clicking function to active it GUI or other specific function.Fortunately, there are not many apps like this

hmm i see

**Comment by end-4** [comment]
@TwelveNight fixed, can you verify?

**Comment by TwelveNight** [comment]
> @TwelveNight fixed, can you verify?

It works well🐮

**Comment by clsty** [comment]
I can confirm that now this problem appears when I right-click on the bash-polling custom widget.

**Comment by end-4** [comment]
I don't like where this is going. I want a large click area. I could un-allow right click and middle click actions for custom widgets and there won't be this problem, but I don't wanna be Apple

**Comment by clsty** [comment]
> I don't like where this is going. I want a large click area. I could un-allow right click and middle click actions for custom widgets and there won't be this problem, but I don't wanna be Apple

I think a button should be clickable as large as it shows, that's normal, right?
If a button could be activated by clicking away from it, that's not very normal, I guess.

Since we have a `user_options.js` now, maybe we could give user an option to choose this?

**Comment by end-4** [comment]
on second thought the music pill would expand when media is available so fine i guess
