### ISSUE TITLE
[Feature] Support for ollama as AI assistant

### ISSUE THREAD

**Issue by clsty** [end-4/dots-hyprland#346]
**What would you like to be added?**

[ollama](https://github.com/ollama/ollama) support.

**How will it help**

Currently we have gemini and chatgpt support, which both need online account and internet access.
- Ollama does not need any account and it supports running locally.
- it's free.
- Privacy friendly.

**Comment by end-4** [comment]
I'll wait for the guy who made a pr earlier to make a new one (with doubts)
I _might_ see if I can take a look at it and add it myself later but very unlikely as my machine is too slow for it to be practical for me

**Comment by clsty** [comment]
This could also be a good thing for https://github.com/end-4/dots-hyprland/discussions/263 , because
- 100% privacy friendly
- no internet needed

**Comment by catmeowjiao** [comment]
can you add gpt4all or llama.cpp + chatglm.cpp?

**Comment by arlo-phoenix** [comment]
If you want broke man ollama / local llama support: Ollama features an OpenAI compatible API on port 11434 (https://ollama.com/blog/openai-compatibility). I think you can just change ai/proxyUrl in `.config/ags/modules/.configuration/user_options.js`. Otherwise it could also be a custom provider like I did [here](https://github.com/arlo-phoenix/dots-hyprland/commits/ollama_openai_api/). It's what I'm using right now and imo works well enough to the point a custom ollama service isn't needed (except changing models, but for that general open ai service could just be improved)

This is also compatible with other local llm options as long as they have an open ai compatible webserver (which most do). I personally use the llama.cpp server directly and start it with
```bash
# just use a very high -ngl like 1000 to run it fully on GPU
./llama.cpp/build/bin/server -ngl 1000 --port 11434 --model /path/to/model
```

**Comment by end-4** [comment]
done in #532 i guess
