### ISSUE TITLE
[Issue] Overview workspace view doesn't scale properly with set DPI and force_zero_scaling

### ISSUE THREAD

**Issue by tcharchar** [end-4/dots-hyprland#424]
- **(For usage) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/02usage)**
- **(For troubleshooting) I have read the [wiki](https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting)**
- Linux distro: Arch Linux x86_64, Kernel 6.8.6-zen1-1-zen

---
## The issue

EDIT: Forgot to mention, but I'm using `wlr-randr --scale 1.25`
As title mentions, for some reason having `xwayland{ force_zero_scaling = true }` messes up with the overview widget, specifically the workspace preview. See image below:
![image](https://github.com/end-4/dots-hyprland/assets/110164189/dcb87669-17a1-49fc-a7f3-8b1b300937f0)

**Comment by end-4** [comment]
maybe adjust overview scale in user config?

**Comment by tcharchar** [comment]
> maybe adjust overview scale in user config?
Looks better, but the issue of apps not properly filling up the preview is still present.

![image](https://github.com/end-4/dots-hyprland/assets/110164189/165ae55a-982a-4947-81a5-1022b234956b)

**Comment by alok-debnath** [comment]
You can reduce the number of workspaces shown from 10 to 8, that's how I fixed mine. I current don't have access to my laptop, will update this reply shortly.

**Comment by tcharchar** [comment]
Changing the number of columms from 10 to 8 makes it now fit without changing the scale from its base 0.18 value, but it still has the issue of not properly filling up a workspace preview.
![image](https://github.com/end-4/dots-hyprland/assets/110164189/fadf8850-656c-4681-a6e3-7502d6d3763a)

**Comment by DiXN** [comment]
What I have done in the past, is to divide the width / height by the current scale in `variables.js` :

```
export const SCREEN_WIDTH = Number(exec(`bash -c "hyprctl monitors -j | gojq '.[].width / .[].scale' | awk '{print int($1+0.5)}'"`));
export const SCREEN_HEIGHT = Number(exec(`bash -c "hyprctl monitors -j | gojq '.[].height / .[].scale' | awk '{print int($1+0.5)}'"`));
```
However, this approach has some flaws. This approach only works with Hyprland and does not work with multiple monitors. In order to solve this problem, I think there has to be a screen width and a screen height per monitor and the actual screen size after scaling has to be determined.

**Comment by tcharchar** [comment]
@DiXN This actually fixes a multitude of problems, including #417 too.

**Comment by DiXN** [comment]
With the following snippet, I can get the screen width and screen height after scaling for each monitor.
```
const SCREEN_GEOMETRY = {}

range(Gdk.Display.get_default()?.get_n_monitors() || 1, 0).forEach(id => {
    const display = Gdk.Display.get_default()
    const monitor = display.get_monitor(id)
    const monitor_geometry = monitor.get_geometry()

    let monitor_obj = {}
    monitor_obj[id] = {
        width: monitor_geometry.width,
        height: monitor_geometry.height,
    }

    Object.assign(SCREEN_GEOMETRY, monitor_obj)
});
````
The idea would be to export `SCREEN_GEOMETRY` and to get the screen geometry of the monitor by indexing `SCREEN_GEOMETRY` with the monitor's id like so `SCREEN_GEOMETRY[id]`. 

For now, I am not sure how, for example, the overview is created per monitor, and therefore I set the screen width and height like this:

```
// Screen size
export const SCREEN_WIDTH = SCREEN_GEOMETRY[0].width;
export const SCREEN_HEIGHT = SCREEN_GEOMETRY[0].height;
```

This, of course, only works with one monitor. @end-4 would this concept help to set the size of the overview per monitor?

**Comment by midn8hustlr** [comment]
I don't think end-4 uses a secondary monitor, and would be difficult to fix these kinds to issues at their end. I guess at this point we all should sponsor a monitor to end-4 🤓.

**Comment by clsty** [comment]
Considering about my economic status, I'm not able to help with that :/

But if @end-4 has a spare device which can run a VNC client, the following steps may provide a second "monitor":

- Install a VNC client on that spare device.
- On host computer, create virtual output according to [Hyprland Wiki](https://wiki.hyprland.org/Configuring/Using-hyprctl/#output)
  - Command: `hyprctl output create headless`
- Run wayvnc to share that virtual output.
- On the VNC client, connect the VNC server. Usually They need to be under the same network.

**Comment by Ate329** [comment]
> What I have done in the past, is to divide the width / height by the current scale in `variables.js` :
> 
> ```
> export const SCREEN_WIDTH = Number(exec(`bash -c "hyprctl monitors -j | gojq '.[].width / .[].scale' | awk '{print int($1+0.5)}'"`));
> export const SCREEN_HEIGHT = Number(exec(`bash -c "hyprctl monitors -j | gojq '.[].height / .[].scale' | awk '{print int($1+0.5)}'"`));
> ```
> 
> However, this approach has some flaws. This approach only works with Hyprland and does not work with multiple monitors. In order to solve this problem, I think there has to be a screen width and a screen height per monitor and the actual screen size after scaling has to be determined.

Thanks a lot!!! This solved my problem as well!

**Comment by end-4** [comment]
~~Sorry guys I've been gaming xd~~
The issue lies in how when there's non-1 scaling, monitor size is reported as is, but window sizes are scaled. The above commit divides monitor dimensions by its scale, which should solve this 
Test please? : )

**Comment by DiXN** [comment]
This unfortunately does not work as well as #436 does for me because Hyprland requires to have a clean divisor for scaling. In my case this is 1.066667 for the resolution 3440x1440. ` hyprctl monitors -j` reports the rounded scale, which in my case is 1.07. 3440 / 1.07 = 3214.95 when it should be 3440 / 1.066667 = 3225. Because of the wrong calculation, there is now a gap on the side when the session menu is open. `GDK`  uses the proper scale for the division. Maybe there is also a way to achieve this with `hyprctl`. I realize this is a special case, but it would still be nice if it could be solved.

![image](https://github.com/end-4/dots-hyprland/assets/16279021/051a821f-bb6d-4460-9ca2-1b32c1d782b5)

On another note, I can see from the commit log of https://github.com/end-4/dots-hyprland/commit/18de9e2fea19f919dce04c1a6dafa7b49903716a that there have been multiple adjustments made, to set the size of the elements according to the individual monitor, however when testing on a setup with two monitors with different resolutions, it still seems to use the resolution of the first monitor.

**Comment by end-4** [comment]
So Gdk just reports the scaled monitor size?

**Comment by end-4** [comment]
okay

**Comment by tcharchar** [comment]
I've recently done a full clean install of arch and this theming script, and I can confirm scaling works out of the box now. Should've closed this sooner, my apologies!

**Comment by end-4** [comment]
@DiXN since Gdk doesn't reliably report the scaled monitor size in all cases (causing #537), I made it so that by default manual division is used to get that data
if you ever update, for your case, set `userOptions.monitors.scaleMethod` to `gdk`
