### ISSUE TITLE
The _GNOME settings_ crashes as soon as I click _multitasking_ in it . 

### ISSUE THREAD

**Issue by fjh1997** [end-4/dots-hyprland#446]
- Linux distro: 
- LSB Version:    n/a
- Distributor ID: Arch
- Description:    Arch Linux
- Release:        rolling
- Codename:       n/a---
## The issue

The _GNOME settings_ crashes as soon as I click _multitasking_ in it . 

![a](https://github.com/end-4/dots-hyprland/assets/25281816/5d274144-fe8d-4f1b-8d63-12999dd57927)

<details>
<summary>Click to expand</summary>

```plain
(com.github.Aylur.ags:1293): Gjs-WARNING **: 18:49:43.300: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
execAsync@resource:///com/github/Aylur/ags/utils/exec.js:4:12
onClicked@file:///home/catcatyu/.config/ags/modules/sideright/quicktoggles.js:216:18
Button/<@resource:///com/github/Aylur/ags/widgets/button.js:28:44
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34```

</details>

**Comment by end-4** [comment]
It doesn't crash for me, and it doesn't matter. Settings in that section won't work in Hyprland anyway
That control center isn't even meant to be ran outside of GNOME in the first place, so don't expect everything there to work well

**Comment by fjh1997** [comment]
> It doesn't crash for me, and it doesn't matter. Settings in that section won't work in Hyprland anyway That control center isn't even meant to be ran outside of GNOME in the first place, so don't expect everything there to work well

Thank you,I know It doesn't work,but I want to make it not crash in case I accidentlly click it , any advices?

**Comment by H0mire** [comment]
> > It doesn't crash for me, and it doesn't matter. Settings in that section won't work in Hyprland anyway That control center isn't even meant to be ran outside of GNOME in the first place, so don't expect everything there to work well
> 
> Thank you,I know It doesn't work,but I want to make it not crash in case I accidentlly click it , any advices?

It happens if you install hyprland and these dots from a minimal linux installation. It appears that some gnome dependencies are missing. After reinstalling in my case Arch Linux with a full Gnome Environement, the multitasking option does not crash anymore. So check for missing gnome packages.

**Comment by b4shful** [comment]
@end-4 What actually works from gnome-control-center? I wonder is it possible to add/remove panels from it or would that require a custom patch?

If it was easy to remove panels, we could (perhaps optionally) remove the panels from GNOME Settings/gnome-control-center that either crash or don't do anything (the ones that have no effect at all) in Hyprland.

Some research (no idea if any of these ideas are viable):
https://discourse.nixos.org/t/how-to-disable-some-panels-in-gnome-control-center/36048
https://askubuntu.com/questions/442520/is-it-possible-to-remove-items-from-system-settings

**Comment by end-4** [comment]
> I wonder is it possible to add/remove panels from it or would that require a custom patch?

That would just be stupid and not worth it. GNOME settings is only a fallback for stuff and isn't going to be a perfect settings app for Hyprland.

**Comment by b4shful** [comment]
> > I wonder is it possible to add/remove panels from it or would that require a custom patch?
> 
> That would just be stupid and not worth it. GNOME settings is only a fallback for stuff and isn't going to be a perfect settings app for Hyprland.
@end-4 

Ok, yes. I said "add/remove" but I actually meant remove, the links I posted were all about removal too.

Just as a note, I tested it out by moving `/usr/share/applications/gnome-multitasking-panel.desktop` out of its folder (to simulate deleting the file) and indeed the panel was completely removed from the GNOME settings menu, and no longer appears in the sidebar.

Some of the panels are completely useless, and some of them crash, however some of them do work fine. It is rather difficult to know which is which, unless the user was to try out every single panel and setting and make a note of which panels are partially working, fully working, not working or crashing (although of course some of them can be educated guesses when you know enough about Wayland). 

Since the settings button in the system sidebar does link to GNOME Settings, so it's part of the interface in a way, and removing panels seems like a trivial matter done by just getting rid of (in some way) the .desktop file for the panel, I think that it would be nice to remove at least the utterly useless panels and the ones that crash...

However, I know that it's a pretty primitive method and could interfere with users who also have a proper GNOME desktop environment installed. So I will just leave this info here in case it's useful for anyone who comes across the issue.
