### ISSUE TITLE
App launcher doesn"t work

### ISSUE THREAD

**Issue by iljo-dp** [end-4/dots-hyprland#5]
So I have installed I think everything that you asked for, I maybe forgot something. But When pressings the mod key, and it opens up the bar to type something in, it never wants to open something, or even fuzzy find something, and just stays empty. And when pressing the windows button on the eww bar, it is just empty, with no Pinned apps or recommended apps. And also no apps in All apps. And when pressing windows + D (it opens the weird GUI thingy, with a lot of stats) the search bar also doesn't let me open things. So I can't launch stuff ynless I open it via the terminal. Did I forget to install something?

**Comment by end-4** [comment]
Hi,
- Could you check the files `scripts/cache/entrynames.txt` and `scripts/cache/entries.txt` (relative to the `eww .yuck`) and see if they contain anything?
- Have you tried restarting (killing eww and launch it again)? 
- Also note that some stuff might not work properly if you don't place the eww folder in ~/.config/

**Comment by CyCodeDE** [comment]
I had the same problem, installed it like the instructions. In the end, the issue was that the `cache` folder was not created in the `.config/eww/scripts/` directory, so the `toggle-overview.sh` couldn't create the files in it. Creating the directory fixed it for me.
@end-4 to fix this, you can just check if the directory exists before trying to write it and create it if not.

**Comment by end-4** [comment]
I see.
https://github.com/end-4/dots-hyprland/commit/5ba01ada1e8eab8da7f03d2bb61ef6fe85f0256f
Does it work well for you once you created the cache folder @CyCodeDE ?

**Comment by CyCodeDE** [comment]
None that I'm aware of. Thanks for fixing. 
I really love your config, so thank you :D.
