### ISSUE TITLE
Media doesn't look right

### ISSUE THREAD

**Issue by nanashi-1** [end-4/dots-hyprland#72]
Is this supposed to look like this?

![image](https://github.com/end-4/dots-hyprland/assets/54083498/e678b595-cc9e-47f8-be27-552ce1512c25)

**Comment by end-4** [comment]
there should be cover art
have you installed the plasma browser integration stuff? the `plasma-browser-integration` package and the browser extension
![image](https://github.com/end-4/dots-hyprland/assets/97237370/886557db-0a95-438f-abca-22c64376cc76)
there should be audio visualizer columns too but there are problems due to cava's changes. i'll investigate that

**Comment by nanashi-1** [comment]
sorry for not mentioning, but will it not work with amberol?

**Comment by end-4** [comment]
can you try again?

**Comment by end-4** [comment]
ugh
it's just that my script fails to treat local music properly 
that player does give the nececssary information
![image](https://github.com/end-4/dots-hyprland/assets/97237370/a4d52f51-38ff-4aaf-8cd5-3acc9887535a)
