### ISSUE TITLE
[Issue] Foot terminal transparent

### ISSUE THREAD

**Issue by zVSciy** [end-4/dots-hyprland#911]
- I have read the Usage and Troubleshooting pages of the wiki: https://end-4.github.io/dots-hyprland-wiki/en/i-i/03troubleshooting/
- I have made sure that both my config and system packages are up to date
- Linux distro: Arch Linux

---
## The issue
So I tried to make the foot terminal transparent, but it doesn't work for me. I've been looking for a solution for days now.
I tried to change the color settings in the foot.ini file as shown below:
```
[colors]
alpha=0.9
foreground=ffffff
background=000000
```

I found a solution in your closed issues, but it didn't work for me. It said to change a variable in the applycolors.sh. I have two of them, so I changed both, but it didn't work:

```
term_alpha=70 #Set this to < 100 make all your terminals transparent
term_alpha=70 #Set this to < 100 make all your terminals transparent
```

+ discord streams are not working idk how to fix, i tried so much
+ nvidia-settings not working anymore 

but those 2 are only small problems hope someone can help me

**Comment by MirilRetry** [comment]
Your issue seems similar to #905, Solution: https://github.com/end-4/dots-hyprland/issues/905#issuecomment-2447066298, to only make foot transparent replace the `.*` with `^(foot)$` [Window Rules Documentation](https://wiki.hyprland.org/Configuring/Window-Rules/)

**Comment by zVSciy** [comment]
It worked!! :) Many thanks
```
windowrule = opacity 0.89, foot
```

This fixed it

**Comment by soloopooo** [comment]
> It worked!! :) Many thanks
> 
> ```
> windowrule = opacity 0.89, foot
> ```
> 
> This fixed it

This fix method is not right.

This transparency will affect the letters' opacity too. You can try to set this to 0 and see what will happen.

The Real bug here is the `applycolor.sh`:

` sed -i "s/\$alpha/$term_alpha/g" "$CACHE_DIR/user/generated/terminal/sequences.txt"`

For unknown reason, the `$alpha` is not set with right opacity, and then the sequences.txt is not modified.

The Best solution is edit your `$CACHE_DIR/user/generated/terminal/sequences.txt`:

You will find this:
`...[]11;[100]...`

![图片](https://github.com/user-attachments/assets/6fa86c2f-8ec0-4c11-8139-cdca6c107864)

Edit this 100 to a number less than 100, then restart foot:

![图片](https://github.com/user-attachments/assets/8ea2cf55-81bf-4399-abba-d25d32d56cb1)

**Comment by MirilRetry** [comment]
> The Real bug here is the `applycolor.sh`:
> 
> ` sed -i "s/\$alpha/$term_alpha/g" "$CACHE_DIR/user/generated/terminal/sequences.txt"`
> 
> For unknown reason, the `$alpha` is not set with right opacity, and then the sequences.txt is not modified.

Not really a bug, It's replacing `$alpha` with `$term_alpha` correctly ([100](https://github.com/end-4/dots-hyprland/blob/6acb6ea7cb4a26fa181a03829f8788da135d1ac0/.config/ags/scripts/color_generation/applycolor.sh#L10) in this case), in commit https://github.com/end-4/dots-hyprland/commit/db5b866c2a36a999654901085f86c0d442e8c33b `term_alpha` value was changed from 80 to 100.
