### ISSUE TITLE
The notification process spawns a zombie process after each notification

### ISSUE THREAD

**Issue by awarewen** [end-4/dots-hyprland#96]
The notification process spawns a zombie process after each notification.

![图片](https://github.com/end-4/dots-hyprland/assets/53365857/75a2a724-b9e8-4c0f-b292-7da320614723)

--- 

In the case of a notification center, it is unreasonable to still use buttons to clear the remaining notifications on the screen. There should be a reasonable notification timeout clearing mechanism.

![图片](https://github.com/end-4/dots-hyprland/assets/53365857/e8ff4db5-3e4f-4108-b39a-5c2208914c3e)

Also, thank you for this awesome dotfile rice.

**Comment by end-4** [comment]
- i can confirm that it does happen 
- those processes are the [notification-on-receive.sh](https://github.com/end-4/dots-hyprland/blob/m3ww/.config/eww/scripts/notification-on-receive.sh) script, which should run once then exit :thinking:
- it might be due to the way the scripts are run by the notify-receive notification daemon. i have no rust knowledge and used a random solution that just worked and didn't notice this. so i'll see if i can do something about it
